name: instudy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  page_transition: ^2.1.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  shimmer_pro: ^0.0.6
  dio: ^5.4.3+1
  cached_video_player_plus: ^3.0.3
  multi_dropdown: ^3.0.1
  visibility_detector: ^0.4.0+2
  gap: ^3.0.1
  flutter_secure_storage: ^9.2.2
  scrollview_observer: ^1.21.2
  flutter_animated_dialog: ^2.0.1
  flutter_spinkit: ^5.2.1
  autoscale_tabbarview: ^1.0.2
  provider: ^6.1.2
  get_time_ago: ^2.0.0
  skeletonizer: ^1.4.2
  easy_debounce: ^2.0.3
  video_thumbnail: ^0.5.3
  flutter_staggered_grid_view: ^0.7.0
  expandable_page_view: ^1.0.17
  typewritertext: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
